"""
initial

Revision ID: 1bd2a2cc8d64
Revises: None
Create Date: 2013-05-28 10:23:52.224582
"""

# revision identifiers, used by Alembic.
revision = '1bd2a2cc8d64'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
