"""init

Revision ID: 3c620e6f2983
Revises: None
Create Date: 2013-05-22 19:51:24.187589

"""

# revision identifiers, used by Alembic.
revision = '3c620e6f2983'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
